### ISSUE TITLE
Extra semicolons in properties with functions

### ISSUE THREAD

**Issue by christianmemije** [txs1992/stylus-converter#76]
Extra semicolons in properties with functions

Input
```stylus
div
  animation: name_of_animation 0.8s cubic-bezier(0.36, 0.07, 0.19, 0.97) both
  background:
    linear-gradient(white 30%, hsla(0, 0%, 100%, 0)),
    linear-gradient(hsla(0, 0%, 100%, 0) 10px, white 70%) bottom,
    radial-gradient(at top, rgba(0, 0, 0, 0.2), transparent 70%),
    radial-gradient(at bottom, rgba(0, 0, 0, 0.2), transparent 70%) bottom
```
Current output
```scss
div {
  animation: name_of_animation 0.8s cubic-bezier(0.36, 0.07, 0.19, 0.97) both;;
  background: linear-gradient(white 30%, hsla(0, 0%, 100%, 0)), linear-gradient(hsla(0, 0%, 100%, 0) 10px, white 70%) bottom;, radial-gradient(at top, rgba(0, 0, 0, 0.2), transparent 70%), radial-gradient(at bottom, rgba(0, 0, 0, 0.2), transparent 70%) bottom;;;
}
```
Expected output
```scss
div {
  animation: name_of_animation 0.8s cubic-bezier(0.36, 0.07, 0.19, 0.97) both;
  background:
    linear-gradient(white 30%, hsla(0, 0%, 100%, 0)),
    linear-gradient(hsla(0, 0%, 100%, 0) 10px, white 70%) bottom,
    radial-gradient(at top, rgba(0, 0, 0, 0.2), transparent 70%),
    radial-gradient(at bottom, rgba(0, 0, 0, 0.2), transparent 70%) bottom;
}
```
