### ISSUE TITLE
对变量的判定问题

### ISSUE THREAD

**Issue by lialosiu** [txs1992/stylus-converter#80]
原stylus：

```stylus
.test 
  right 10px
  text-align right
```

编译后的scss：

```scss
.test  {
  right: 10px;
  text-align: 10px;
}
```

会将 right 判定为是变量，从而导致下面 text-align right 中的 right 被当成变量赋值为了 10px

按Styuls的规范，应该是 = 号左边的才判定为变量名吧...
