### ISSUE TITLE
Missing newline for "Group"

### ISSUE THREAD

**Issue by knilink** [txs1992/stylus-converter#97]
intput:
```styl
.foo
  height:1px
  .bar
    height:2px
```
expected:
```scss
.foo {
  height: 1px;
  .bar {
    height: 2px;
  }
}
```
actual:
```scss
.foo {
  height: 1px;.bar {
    height: 2px;
  }
}
```
