### ISSUE TITLE
Boken prop reference with operator

### ISSUE THREAD

**Issue by knilink** [txs1992/stylus-converter#98]
input
```styl
.foo
  width: 1px
  height: -@width
```
expected:
```scss
.foo {
  width: 1px;
  height: -1px;
}
```
actual:
```
TypeError: Cannot read property 'map' of undefined
```
